---
title: "project"
author: "Keerthana"
output:
  html_document: default
---

### This file reproduces the reuslts from the reference paper. It appiles KNN and SVM classifier and does LOSO and s-LOO cross validation.

```{r}
library(caret)
library(class)
library(ISLR)
# loading training data
data_train <- read.table("train_data.txt",sep=",",row.names=NULL,col.names=c("subject id", "jitter1","jitter2","jitter3","jitter4","jitter5","shimmer1","shimmer2","shimmer3","shimmer4","shimmer5","shimmer6","AC","NTH","HTN","median pitch","mean pitch","sd","min pitch","max pitch","num pulses","Number of periods","Mean period","Standard deviation of period","Fraction of locally unvoiced frames","Number of voice breaks","Degree of voice breaks","UPDRS","class"),fill=FALSE)
train_data=data_train[,1:27]
train_response=data_train[,29]

# loading test data
data_test <- read.table("test_data.txt",sep=",",row.names=NULL,col.names=c("subject id", "jitter1","jitter2","jitter3","jitter4","jitter5","shimmer1","shimmer2","shimmer3","shimmer4","shimmer5","shimmer6","AC","NTH","HTN","median pitch","mean pitch","sd","min pitch","max pitch","num pulses","Number of periods","Mean period","Standard deviation of period","Fraction of locally unvoiced frames","Number of voice breaks","Degree of voice breaks","class"),fill=FALSE)
test_data=data_test[,1:27]
test_response=data_test[,28]

```


```{r}
# standardise the data
train_data_norm=scale(train_data[,2:27])
test_data_norm=scale(test_data[,2:27])
```

### LOSO KNN
```{r}
# CV LOSO KNN
TN=matrix(0,40,1)
TP=matrix(0,40,1)
FN=matrix(0,40,1)
FP=matrix(0,40,1)
acc=matrix(0,40,1)
for (i in 0:39) {
pred<- knn(train_data_norm[-((i*26+1):(i*26+26)),],train_data_norm[((i*26+1):(i*26+26)),],train_response[-((i*26+1):(i*26+26))], k=7)
test_truth=train_response[((i*26+1):(i*26+26))]
for (j in 1:26)
  if(pred[j]==test_truth[j])
  {
    if(pred[j]==0)
      TN[i+1]=TN[i+1]+1
    else
      TP[i+1]=TP[i+1]+1
  }
  else
  {
    if(pred[j]==0)
      FN[i+1]=FN[i+1]+1
    else
      FP[i+1]=FP[i+1]+1
  }
 }
FN=sum(FN)
TN=sum(TN)
FP=sum(FP)
TP=sum(TP)
acc=(TP+TN)/1040
sensi=TP/(TP+FN)
speci=TN/(TN+FP)
MCC=(TP*TN-FP*FN)/sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

acc
sensi
speci
MCC
```

### LOSO SVM
```{r}
# CV LOSO SVM
library(e1071)
TN=matrix(0,40,1)
TP=matrix(0,40,1)
FN=matrix(0,40,1)
FP=matrix(0,40,1)
acc=matrix(0,40,1)
for (i in 0:39) {
train_data_frame=data.frame(x=train_data_norm[-((i*26+1):(i*26+26)),],y=train_response[-((i*26+1):(i*26+26))])
svm_model<-svm(y ~ ., data = train_data_frame, type= "C-classification",kernel="linear")
test_data_frame=data.frame(x=train_data_norm[((i*26+1):(i*26+26)),],y=train_response[((i*26+1):(i*26+26))])
pred<-predict(svm_model,test_data_frame)

test_truth=train_response[((i*26+1):(i*26+26))]
for (j in 1:26)
  if(pred[j]==test_truth[j])
  {
    if(pred[j]==0)
      TN[i+1]=TN[i+1]+1
    else
      TP[i+1]=TP[i+1]+1
  }
  else
  {
    if(pred[j]==0)
      FN[i+1]=FN[i+1]+1
    else
      FP[i+1]=FP[i+1]+1
  }
}
FN=sum(FN)
TN=sum(TN)
FP=sum(FP)
TP=sum(TP)
acc=(TP+TN)/1040
sensi=TP/(TP+FN)
speci=TN/(TN+FP)
MCC=(TP*TN-FP*FN)/sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

acc
sensi
speci
MCC
```

### Summarizing the dataset using central tendency and dispersion metrics

```{r}

train_mat1=matrix(0,40,52) # mean and sd dataset
train_mat2=matrix(0,40,52) # median and mean absolute deviation dataset
train_mat3=matrix(0,40,52) # trimmed mean and interquartile range dataset
train_response_mat=matrix(0,40,1) # combine all
for (i in 0:39){
for (j in 1:26){
l=i*26+1
m=i*26+26
train_mat1[i+1,j]=mean(train_data_norm[l:m,j])
train_mat2[i+1,j]=median(train_data_norm[l:m,j])
train_mat3[i+1,j]=mean(train_data_norm[l:m,j],trim = 0.125)

train_mat1[i+1,j+26]=sd(train_data_norm[l:m,j])
train_mat2[i+1,j+26]=mad(train_data_norm[l:m,j])
train_mat3[i+1,j+26]=IQR(train_data_norm[l:m,j])

}
train_response_mat[i+1]=train_response[i*26+1]
}

test_mat1=matrix(0,28,52)# mean and sd dataset
test_mat2=matrix(0,28,52)# median and mean absolute deviation dataset
test_mat3=matrix(0,28,52)# trimmed mean and interquartile range dataset
test_response_mat=matrix(0,28,1) # combine all
for (i in 0:27){
for (j in 1:26){
l=i*6+1
m=i*6+6
test_mat1[i+1,j]=mean(test_data_norm[l:m,j])
test_mat2[i+1,j]=median(test_data_norm[l:m,j])
test_mat3[i+1,j]=mean(test_data_norm[l:m,j],trim = 0.125)

test_mat1[i+1,j+26]=sd(test_data_norm[l:m,j])
test_mat2[i+1,j+26]=mad(test_data_norm[l:m,j])
test_mat3[i+1,j+26]=IQR(test_data_norm[l:m,j])
}
  test_response_mat[i+1]=test_response[i*6+1]
}
train_mat=cbind(train_mat1,train_mat2,train_mat3)
test_mat=cbind(test_mat1,test_mat2,test_mat3)

# standardising the data set
train_mat1=scale(train_mat1)
train_mat2=scale(train_mat2)
train_mat3=scale(train_mat3)
train_mat=scale(train_mat)

test_mat1=scale(test_mat1)
test_mat2=scale(test_mat2)
test_mat3=scale(test_mat3)
test_mat=scale(test_mat)

```

### s-LOO SVM
```{r}
# apply SVM cross validation LOOCV

library(e1071)
TN=0
TP=0
FN=0
FP=0
acc_val=matrix(0,40,1)
for (i in 1:40) {
train_mat1_frame=data.frame(x=train_mat3[-i,],y=train_response_mat[-i]) 
svm_Linear<-svm(y ~ ., data = train_mat1_frame, type="C-classification", kernel="linear")
test_val=data.frame(x=t(train_mat3[i,]),y=t(train_response_mat[i]))
pred<-predict(svm_Linear,test_val)

# test_val2=data.frame(x=test_mat,y=test_response_mat)
# pred2<-predict(svm_Linear,test_val2)
acc_val[i]=mean(pred==test_val$y)
if(test_val$y==pred)

  {
    if(pred==0)
      TN=TN+1
    else
      TP=TP+1
  }
  else
  {
    if(pred==0)
      FN=FN+1
    else
      FP=FP+1
  }

 }
acc=(TP+TN)/40
sensi=TP/(TP+FN)
speci=TN/(TN+FP)
MCC=(TP*TN-FP*FN)/sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

acc
sensi
speci
MCC

```

### s-LOO KNN

```{r}
# apply knn cross validation LOOCV


TN=0
TP=0
FN=0
FP=0
acc=matrix(0,40,1)
for (i in 1:40) {
pred<- knn(train_mat1[-i,],train_mat1[i,],train_response_mat[-i], k=7)
# pred<-knn(train_mat3[-i,],test_mat3,train_response_mat[-i], k=7)
# acc[i]=mean(test_response_mat==pred)
if(train_response_mat[i]==pred)

  {
    if(pred==0)
      TN=TN+1
    else
      TP=TP+1
  }
  else
  {
    if(pred==0)
      FN=FN+1
    else
      FP=FP+1
  }

}
acc=(TP+TN)/40
sensi=TP/(TP+FN)
speci=TN/(TN+FP)
MCC=(TP*TN-FP*FN)/sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

acc
sensi
speci
MCC
```

