---
title: "project_randomforest"
author: "Keerthana"
date: "May 1, 2018"
output: html_document
---
### This file implements Random Forest method and computes performance
```{r}
library(caret)
library(class)
library(ISLR)
# loading training data
data_train <- read.table("train_data.txt",sep=",",row.names=NULL,col.names=c("subject id", "jitter1","jitter2","jitter3","jitter4","jitter5","shimmer1","shimmer2","shimmer3","shimmer4","shimmer5","shimmer6","AC","NTH","HTN","median pitch","mean pitch","sd","min pitch","max pitch","num pulses","Number of periods","Mean period","Standard deviation of period","Fraction of locally unvoiced frames","Number of voice breaks","Degree of voice breaks","UPDRS","class"),fill=FALSE)
train_data=data_train[,1:27]
train_response=data_train[,29]

# loading test data
data_test <- read.table("test_data.txt",sep=",",row.names=NULL,col.names=c("subject id", "jitter1","jitter2","jitter3","jitter4","jitter5","shimmer1","shimmer2","shimmer3","shimmer4","shimmer5","shimmer6","AC","NTH","HTN","median pitch","mean pitch","sd","min pitch","max pitch","num pulses","Number of periods","Mean period","Standard deviation of period","Fraction of locally unvoiced frames","Number of voice breaks","Degree of voice breaks","class"),fill=FALSE)
test_data=data_test[,1:27]
test_response=data_test[,28]

```

### Seperate data and class response from the loaded input data
```{r}
train_data_norm=(train_data[,2:27])
test_data_norm=(test_data[,2:27])
train_response=as.factor(train_response)
test_response=as.factor(test_response)

```

### LOSO Random Forest
```{r}
# LOSO

# Uncomment the following code to test LOSO for 14 best feature dataset. Otherwise run the code for 26 features

#train_data_norm=train_data_norm[,c(2,6,10,12,13,14,17,18,19,20,21,24,25,26)]
library(randomForest)
TN=matrix(0,40,1)
TP=matrix(0,40,1)
FN=matrix(0,40,1)
FP=matrix(0,40,1)
acc=matrix(0,40,1)
for (i in 0:39){
model_RF<-randomForest(train_data_norm[-((i*26+1):(i*26+26)),],train_response[-((i*26+1):(i*26+26))],importance = TRUE)
 pred<-predict(model_RF,train_data_norm[((i*26+1):(i*26+26)),])

 
 test_truth=train_response[((i*26+1):(i*26+26))]
 for (j in 1:26)
   if(pred[j]==test_truth[j])
   {
     if(pred[j]==0)
       TN[i+1]=TN[i+1]+1
     else
       TP[i+1]=TP[i+1]+1
   }
   else
   {
     if(pred[j]==0)
       FN[i+1]=FN[i+1]+1
     else
       FP[i+1]=FP[i+1]+1
   }
 }
 FN=sum(FN)
 TN=sum(TN)
 FP=sum(FP)
 TP=sum(TP)
 acc=(TP+TN)/1040
 sensi=TP/(TP+FN)
 speci=TN/(TN+FP)
 MCC=(TP*TN-FP*FN)/sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

acc
sensi
speci
MCC
```
### summarizing the dataset using central tendency and dispersion metrics
```{r}
# mean and standard deviation dataset
train_mat1=matrix(0,40,52)
train_mat2=matrix(0,40,52)
train_mat3=matrix(0,40,52)
train_response_mat=matrix(0,40,1)
for (i in 0:39){
for (j in 1:26){
l=i*26+1
m=i*26+26
train_mat1[i+1,j]=mean(train_data_norm[l:m,j])
train_mat2[i+1,j]=median(train_data_norm[l:m,j])
train_mat3[i+1,j]=mean(train_data_norm[l:m,j],trim = 0.125)

train_mat1[i+1,j+26]=sd(train_data_norm[l:m,j])
train_mat2[i+1,j+26]=mad(train_data_norm[l:m,j])
train_mat3[i+1,j+26]=IQR(train_data_norm[l:m,j])

}
train_response_mat[i+1]=train_response[i*26+1]
}

train_mat=cbind(train_mat1,train_mat2,train_mat3)
train_response_mat=as.factor(train_response_mat)

```

### Run this section of code when only 14 features are to be selected for summarizing 
```{r}

train_data_norm=train_data_norm[,c(2,6,10,12,13,14,17,18,19,20,21,24,25,26)]
train_mat1=matrix(0,40,28)
train_mat2=matrix(0,40,28)
train_mat3=matrix(0,40,28)
train_response_mat=matrix(0,40,1)
for (i in 0:39){
for (j in 1:14){
l=i*26+1
m=i*26+26
train_mat1[i+1,j]=mean(train_data_norm[l:m,j])
train_mat2[i+1,j]=median(train_data_norm[l:m,j])
train_mat3[i+1,j]=mean(train_data_norm[l:m,j],trim = 0.125)

train_mat1[i+1,j+14]=sd(train_data_norm[l:m,j])
train_mat2[i+1,j+14]=mad(train_data_norm[l:m,j])
train_mat3[i+1,j+14]=IQR(train_data_norm[l:m,j])

}
train_response_mat[i+1]=train_response[i*26+1]
}


train_mat=cbind(train_mat1,train_mat2,train_mat3)
train_response_mat=as.factor(train_response_mat)

```

### s-LOO Random Forest

```{r}
# LOOCV
TN=0
TP=0
FN=0
FP=0

for (i in 1:40) {
model_RF<-randomForest(train_mat2[-i,],train_response_mat[-i],importance = TRUE)
pred<-predict(model_RF,train_mat2[i,])

if(train_response_mat[i]==pred)

  {
    if(pred==1)
      TN=TN+1
    else
      TP=TP+1
  }
  else
  {
    if(pred==2)
      FN=FN+1
    else
      FP=FP+1
  }

 }
acc=(TP+TN)/40
sensi=TP/(TP+FN)
speci=TN/(TN+FP)
MCC=(TP*TN-FP*FN)/sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))

acc
sensi
speci
MCC

```

